version: "2"
services:
  nextjs_nginx:
    container_name: nextjs_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./out:/var/www
    ports:
      - 8091:8091
    networks: 
      - memberhub_back
networks:
  memberhub_back:
    external: true