name: Deploy to staging (DigitalOcean)

on: 
  push: 
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x]

    steps:
    - uses: actions/checkout@v2.1.0
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm run build

    - name: Deploy files via scp
      uses: appleboy/scp-action@master 
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./out"
        target: "frontend"