name: Testing Workflow dispatch

on: workflow_dispatch

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # This is required for actions/checkout@v2
    steps:
    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.AWS_ECS_STAGING_SERVICE }} ${{ secrets.AWS_ECS_SERVICE }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python