name: Production Build and Test

on:
  push:
    branches: [ deploy ]

jobs:
  trigger_playwright_test:
    uses: ./.github/workflows/playwright-test.yml 

  detect-test-result:
    needs: [ trigger_playwright_test ]
    runs-on: ubuntu-latest

    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Read Test Result
        id: testinfo
        run: |
          status=$(jq -r '.status' last-run.json)
          echo "status=$status" >> $GITHUB_OUTPUT
      
      - name: Deploy to Production
        if: steps.testinfo.outputs.status == 'passed'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-to-aws.yml',
              ref: 'deploy'
            });
